services:
  - type: web
    name: fightclub-backend
    env: node
    plan: free
    buildCommand: cd apps/backend && npm install && npm run build
    startCommand: cd apps/backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LEONARDO_API_KEY
        sync: false
      - key: LEONARDO_API_BASE
        sync: false
