export enum CharacterReportReason {
  INAPPROPRIATE = 'INAPPROPRIATE',
  HATE_SPEECH = 'HATE_SPEECH',
  GRAPHIC_VIOLENCE = 'GRAPHIC_VIOLENCE',
  IMPERSONATION = 'IMPERSONATION',
  SPAM = 'SPAM',
  HARASSMENT = 'HARASSMENT',
  NSFW = 'NSFW',
  TOS_VIOLATION = 'TOS_VIOLATION',
  LOW_QUALITY = 'LOW_QUALITY',
  UNINTELLIGIBLE = 'UNINTELLIGIBLE',
  COPYRIGHTED_CONTENT = 'COPYRIGHTED_CONTENT',
  OTHER = 'OTHER',
}
