name: Backend CI

on:
  push:
    paths:
      - 'apps/backend/**'
  pull_request:
    paths:
      - 'apps/backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fightclub_test
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/fightclub_test
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LEONARDO_API_KEY: ${{ secrets.LEONARDO_API_KEY }}
      LEONARDO_API_BASE: ${{ secrets.LEONARDO_API_BASE }}

    defaults:
      run:
        working-directory: ./apps/backend

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run DB Migrations
        run: npx prisma migrate deploy

      - name: Prepare DB
        run: npm run test:prepare

      - name: Run Tests
        run: npm run test
