# .github/workflows/deploy-migrations.yml
name: Deploy Fight Club Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚢 Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}

